[project]
name = 'Cosmic-String-Manipulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cosmic-string-management]
path = 'contracts/cosmic-string-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.cosmic-string-nft]
path = 'contracts/cosmic-string-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-extraction-marketplace]
path = 'contracts/energy-extraction-marketplace.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
